### PR TITLE
Add support for logType and references

### PR DESCRIPTION
**Pull request by jewzaam**
### What type of PR is this?
feature

### What this PR does / why we need it?
Add support for logType and references

### Which Jira/Github issue(s) this PR fixes?
New properties for notifications.

logType - https://issues.redhat.com/browse/OSD-18449 
references - https://issues.redhat.com/browse/OSD-18446

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Ran `make generate` command locally to validate code changes
- [ ] Included documentation changes with PR

### CODE REVIEW

**Comment by jewzaam** [comment]
/hold

need https://github.com/openshift/ocm-agent-operator/pull/91 first

**Comment by jewzaam** [comment]
/hold cancel

upstream dependency is merged, ready for review

**Comment by jewzaam** [comment]
/hold

Need to hold for the Service Log change to add `references`.

**Comment by jewzaam** [comment]
/hold cancel

New OSL field `doc_references` added and the PR is adjusted.  Ready for review.

**Comment by bmeng** [comment]
Hi @jewzaam , what is the Service Log change you mentioned? could you link it here?
And as the new fields are optional, I do not think the SL side change will block this as well.

**Comment by jewzaam** [comment]
> Hi @jewzaam , what is the Service Log change you mentioned? could you link it here? And as the new fields are optional, I do not think the SL side change will block this as well.

https://issues.redhat.com/browse/OCM-3671 is where `doc_references` work is tracked.  New fields are optional so we do not break existing notifications.  We need to iterate on this to get to the final goal of required severity, log_type, and doc_references.  This PR is the first step of enabling our use of fields.  Once we _use_ the fields in all the places we can make the CRD required and modify OSL to be required.  Note it also requires OCM / CS changes.

**Comment by bmeng** [comment]
Thanks!

/lgtm

**Pull request merged**
