### PR TITLE
[OSD-8947] ocm-agent skeleton code

### PR DESCRIPTION
**Pull request by a7vicky**
This is basic skeleton for ocm-agent webserver.
https://issues.redhat.com/browse/OSD-8947

### CODE REVIEW

**Comment by T0MASD** [comment]
structure looks good for the skeleton also tried running it locally. No makefile or instructions is intentional as these parts have not been decided and we expect the code to change significantly in the near future.

/lgtm

**Comment by mrbarge** [comment]
I agree this is good enough for a skeleton client, however it'd be good to see the build components as part of this skeleton too.

I have raised a PR to this branch to add those components: https://github.com/a7vicky/ocm-agent/pull/1

@a7vicky if you could please review and merge that PR if you're happy, make any changes if you want to, and then I'll personally be fine to lgtm this.

**Comment by a7vicky** [comment]
Thanks @mrbarge I have run the build  and it's all working without an issue.

**Pull request merged**
