### PR TITLE
Add OcmAgent selectorsyncset for management clusters

### PR DESCRIPTION
**Pull request by hectorakemp**
### What type of PR is this?
_(feature)_

### What this PR does / why we need it?
This pull request demonstrates how to deploy OCM agent in fleet mode on management clusters. 
### Which Jira/Github issue(s) this PR fixes?

_Fixes #_
https://issues.redhat.com/browse/OSD-20371
### Special notes for your reviewer:
Spike doc explaining how to test this: https://docs.google.com/document/d/1nw4XeEftcq67M9Jg9ljJd5W09y-8mE05KHdXxgk5QOk/edit
### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Ran `make generate` command locally to validate code changes
- [ ] Included documentation changes with PR

### CODE REVIEW

**Comment by hectorakemp** [comment]
Depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/99468/diffs being merged

**Comment by bmeng** [comment]
lgtm

**Pull request merged**
